### ISSUE TITLE
Urfaust misnumbered 2709-2738

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/faust-xml#133]
Die Vershälften von 2709 bilden in U und S einen antilabischen Vers, in A B Ba sind es zwei Verse. Liegt die falsche Alignierung bis Vers 2738 (einschl.) an einem Kodierungsfehler bei den Verszahen in U?? (S ist ja korrekt aligniert.)

![2709ff](https://user-images.githubusercontent.com/26788529/31898101-892dfe36-b818-11e7-8701-b036a1612638.JPG)

**Comment by gerritbruening** [comment]
Ja, da wird die Verszählung verkehrt sein. Schaue ich mir demnächst an.

**Comment by dietmarpravida** [comment]
2709:
````
<l n="2709" part="I" f:nx="u_561" xml:id="u_561_a">Und hier!</l>
                  <stage n="before_2709">(er hebt einen Bettvorhang auf)</stage>
                  <l n="2709" **part="F"** f:nx="u_561" xml:id="u_561_b">Was faßt mich für ein Wonnegraus!</l>
                  <join target="#u_561_a #u_561_b" type="antilabe"/>
````

2338:
```` 
<sp>
               <speaker n="before_2738i">Fauſt</speaker>
               <l f:nx="u_590" xml:id="l_590a" n="2738" **part="I"**>Ich weis nicht ſoll ich?</l>
            </sp>
            <sp>
               <speaker n="before_2738f">
                  <abbr>Meph:</abbr>
               </speaker>
               <l f:nx="u_590" xml:id="l_590b" n="2738" **part="F"**>Fragt ihr viel!</l>
               <join target="#l_590a #l_590b" type="antilabe"/>
````

(`part="I"` und `part="F"` jeweils analog zur Codierung in S eingetragen in https://faust:********@faustedition.uni-wuerzburg.de/xml/print/S(o)_IIIB11-2.xml)

@gerritbruening bitte überprüfen, ob das so korrekt ist (id's bei BAs anpassen?)

**Comment by dietmarpravida** [comment]
change-Vermerk prüfen und dann closen
