### ISSUE TITLE
Zum Schluss: stage followed by stage

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-xml#219]
Hier soll geprüft werden, ob es sich nicht doch um nur eine Bühnenanweisung handelt. @thvitt, wie kann man das per XPath abfragen?

Besonders verdächtig sind solche `stage`-Elemente, wenn sie dieselbe Schröer-Nr. haben (d.h., in der WA ist es nur eine Bühnenanweisung).

**Comment by thvitt** [comment]
//stage[following::*[1][self::stage]]
    //stage[@n = following::*[1][self::stage]/@n]
    //stage[replace(@n, '\D*(\d+).*', '$1') = 
            replace(following::*[1][self::stage]/@n, '\D*(\d+).*', '$1')]

1. selektiert alle stages, auf die unmittelbar eine stage folgt
2. selektiert alle stages, auf die unmittelbar eine stage mit gleichem `n`-Attribut folgt
3. selektiert alle stages, auf die unmittelbar eine stage folgt, wobei der numerische Teil der n-Attribute übereinstimmen muss.

(XPath 2, also faust.xml im Oxygen)

Zur Logik: `following::*` selektiert alle Elemente, die auf die Stage folgen, `[1]` wählt das erste davon aus und `[self::stage]` lässt es nur durch, wenn es sein stage-Element ist. (`following::stage[1]` würde das erste folgende stage-Element wählen, auch wenn da noch welche dazwischen sind).

**Comment by gerritbruening** [comment]
Danke für die Abfragen und die Erklärungen, das glaube ich sogar zu verstehen!

**Comment by gerritbruening** [comment]
Für Faust II habe ich alles geprüft.

**Comment by dietmarpravida** [comment]
> sind die in der WA wirklich zu einer BA zusammengefasst worden und haben deswegen ein- und dieselbe Nummer bekommen?

* before_2260_b nimmt den Bohrer und die folgende BA (selbe Nummer)
-- stehen in WA in einer Zeile
* before_2587_a Die Hexe löst den Kreis und die folgende BA (selbe Nummer)
--  stehen in WA in einer Zeile
* before_3835_b Harzgebirg BA (selbe Nummer)
-- stehen in WA in einer Zeile

**Comment by dietmarpravida** [comment]
Ja, deutlicher Abstand

**Comment by gerritbruening** [comment]
Wenn so in Ordnung, closen.

**Comment by dietmarpravida** [comment]
Was könnte hier denn problematisch sein? Wenn es was gibt, bitte wieder aufmachen.

**Comment by gerritbruening** [comment]
Nö, passt schon.
