### ISSUE TITLE
stage-sentences.xml prüfen

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-xml#382]
https://github.com/faustedition/faust-gen-html/blob/master/text/stage-sentences.xml
Vorgeschichte:
* #253
* #349

**Comment by gerritbruening** [comment]
Können wir da nachher einen gemeinsamen Durchgang machen?

**Comment by gerritbruening** [comment]
MC:
> Wenn ich das System richtig verstehe müsste in Faust I nach folgenden BA ein Punkt gesetzt werden, weil satzwertige BA ohne folgendem Text:
- [ ] Vor 2587: DIE HEXE lös¹t den Kreis
- [ ] Vor 2587: FAUST tritt heraus
- [ ] Vor 3207: MEPHISTOPHELES klopft an
- [ ] Vor 3251: MEPHISTOPHELES tritt auf
- [ ] TTF vor 44: FAUST blickt wild umher

> Nach folgenden BA müsste der Punkt getilgt werden, weil jeweils Text folgt.
- [ ] Vor 2399: SIEBEL trinkt unvorsichtig, der Wein fließt auf die Erde, und wird zur Flamme.
- [ ] Vor 2311 ALTMAYER zieht einen Pfropf aus dem Tisch, es springt ihm Feuer entgegen.
Bitte prüfen.

**Comment by dietmarpravida** [comment]
für den Satz angewiesen, sollen im Lauf der Konsistenzprüfung nachgetragen werden (abgesehen davon stehen sie auch in meiner Liste)

**Comment by dietmarpravida** [comment]
Vorschläge von sh wurden im Satz noch (teilweise) berücksichtigt

**Comment by dietmarpravida** [comment]
Für die digitae Edition nochma checken

**Comment by gerritbruening** [comment]
[Das](https://github.com/faustedition/faust-gen-html/commit/8b0c5b6af5b3b826863c5103bdc0ec9d2e674f38) sollte es jetzt eigentlich sein. @dietmarpravida, bitte um Prüfung.
