### ISSUE TITLE
vor 12057 Versgruppenabstand H

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-xml#434]
> wie bei 11287?

Diese Anmerkung verstehe ich nicht.

**Comment by gerritbruening** [comment]
Dann besser raus damit?

**Comment by dietmarpravida** [comment]
Musst du entscheiden, ob die Auskunft von Interesse ist oder nicht. Ich wäre da nicht so streng und finde die Zahl der Anmerkungen zu F-II ohnehin knapp.
