### ISSUE TITLE
Auftritte in Faust II

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-xml#474]
@dietmarpravida, angesichts von
![grafik](https://user-images.githubusercontent.com/10358005/43327341-74a4c85a-91bb-11e8-9f68-10f3a786a3df.png)
(http://dev.faustedition.net/document?sigil=2_H&page=346&view=facsimile_text#lbefore_11167_b)
frage ich mich, ob es doch Auftritte im Faust II gibt.
Als Unterscheidungskriterium käme in Frage:
* BA außerhalb von Replik ohne Klammern (typischerweise wie hier mit Hervorhebung)
* BA außerhalb von Replik mit Klammern, aber Hervorhebung am Anfang, die außerhalb von Klammern steht (before_11143_b, before_11844_b)

Allerdings sind diese Fälle äußerlich kaum von Quasi-Repliken zu unterscheiden, und deswegen sollte man dieses Fass wohl nicht aufmachen.

**Comment by dietmarpravida** [comment]
kommt das nicht ohnehin darauf an, wie einheitlich das durchgehalten wird? Wenn es nur vereinzelt vorkommt, wäre es ohne großen Wert.
