### ISSUE TITLE
change line numbers in xml-files

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/faust-xml#505]
3184 a Er liebt mich!
3184 b Ja, mein Kind! Laß dieses Blumenwort
3994/3995 [= 1 Vers] Halte! Halte! / Wer ruft da aus der Felsenspalte?

**Comment by dietmarpravida** [comment]
@thvitt  Die drei Verszahlen müssten überall geändert werden, wo sie als unsere Zählung vorkommen (nicht dagegen in WA etc.); wie mache ich das am einfachsten?

**Comment by thvitt** [comment]
ich verstehe die Aufgabenstellung nicht

**Comment by dietmarpravida** [comment]
Überall, wo Versziffernangegeben werden, soll als die in unserer Ausgabe gütige Verzählung bei den (Halb-)Versen:
"Er liebt mich!" ______________________________ die Verszahl "3184 a" stehen
"Ja, mein Kind! Laß dieses Blumenwort" __________________ "3184 b" _______
"Halte! Halte! / Wer ruft da aus der Felsenspalte?" ________"3994/3995" ___

**Comment by thvitt** [comment]
_3184 a_ und _3184 b_ geht nicht für 1.0 (Versziffern mit Suffix oder so)
das andere ist bei den betreffenden Zeugen als `n="3994 3995"` zu codieren.

**Comment by dietmarpravida** [comment]
> das andere ist bei den betreffenden Zeugen als n="3994 3995" zu codieren

done

**Comment by dietmarpravida** [comment]
hier erledigt, 3184a-b jetzt unter #647

**Comment by gerritbruening** [comment]
Bitte nochmal hier schauen:
https://faustedition.uni-wuerzburg.de/new/xml-query/?folder=transcript%2Fsb_berlin&xpath=%2F%2Ftei%3Al[%40n%3D%223993%22]%2Ffollowing%3A%3Atei%3Asp[1]&mode=xml

**Comment by dietmarpravida** [comment]
In der Berliner Hs nachgetragen.

**Comment by dietmarpravida** [comment]
@thvitt Die Suche nach "3994" und nach "3995" ergibt eine 404.

**Comment by thvitt** [comment]
Suche ist ein Extraissue.
