### ISSUE TITLE
4138-4143 m-dashes

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/faust-xml#510]
Die verschieden langeen Gedankenstriche sollten wir doch noch mal vereinheitlichen:

![4138-4143](https://user-images.githubusercontent.com/26788529/43968828-87054dae-9cc8-11e8-840d-5fa1a4861c26.JPG)

**Comment by gerritbruening** [comment]
Was wäre hier für mich zu tun?
Ist der konstituierte Text in Ordnung?

**Comment by dietmarpravida** [comment]
die Zeichen, die im kT stehen, sollten an den angegebenen Stellen entsprechend auch in die Druckdateien eingefügt werden

**Comment by gerritbruening** [comment]
1821
- [ ] S
- [ ] A
- [ ] D.1
- [ ] B
- [ ] D.2
- [ ] B.a
- [ ] 1 H.1
- [ ] C.1 12
- [ ] C.3 12
4138
4142
4143
