### ISSUE TITLE
Update list of editorial decisions

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-xml#542]
https://github.com/faustedition/faust-gen-html/issues/550#issuecomment-404103799

**Comment by gerritbruening** [comment]
Depends on https://github.com/faustedition/faust-gen-html/issues/582

**Comment by gerritbruening** [comment]
@dietmarpravida, gibt es bei dir noch multiple Typenzuweisungen? Die können bei der Zählung Probleme verursachen, wenn das nicht in XML kodiert sind. (Kann sein, dass nicht.)

**Comment by gerritbruening** [comment]
@dietmarpravida, gibt es bei dir noch multiple Typenzuweisungen? Die könnten Probleme verursachen, wenn sie nicht in XML kodiert sind.

**Comment by dietmarpravida** [comment]
- before_354_c[Zimmer]{Zimmer,} vor 354 Zimmer, none]  Zimmer^ H5 	Zimmer, S 	Zimmer^ A B Ba [Typ 1c Typ 2a]
- 359[Und]{Und bin} 359 bin] H5 S  fehlt A 	bin D1 	bin B Ba  [Typ 1a Typ 2a]
- 2348[Doch]{Dich} 2348 Dich] H2  Dich S 	Doch A B Ba H1 C1 C3 [Typ 2a Typ 2c]
- 3990[]{} 3990–4015] Die Verse sind im Druck zweistufig eingerückt (A 8, S. 198–199): 3990–3995 um 5 mm eingerückt, was für Kurzverse normal ist; 3996–3999 auf Seite 198 um 10 mm; ebenso 4000–4003 und 4008–4015 (beidemale wohl versehentlich) sowie 4004–4007 (wohl korrekt) auf Seite 199 um 10 mm.. [Typ 7 Typ 1c]

**Comment by gerritbruening** [comment]
Welche sehen tu ich allerdings nicht.

**Comment by gerritbruening** [comment]
Ich habe die Fälle angesehen und nach Erledigung abgehakt. Alle werden jetzt mit Sonderkodierung behandelt. Bitte den referencing commit prüfen.

**Comment by gerritbruening** [comment]
Das geht so nicht, wir müssen 
[tei-idml_app.pdf](https://github.com/faustedition/xml/files/2333566/tei-idml_app.pdf) morgen nochmal zusammen durchgehen.
Teils hat der Druck einen Überhang an Einträgen, teils sind die Typenzuweisungen anders.

**Comment by dietmarpravida** [comment]
In der generierten Liste fehlen die Einträge:
- IIa: 3620
- IVb: 3620
- VII: vor 2540 
-- statt "vor 3187" muss es heißen "nach 3186"

**Comment by thvitt** [comment]
> In der generierten Liste fehlen die Einträge:
> 
> * IIa: 3620 
> * IVb: 3620

wurde gar nicht als Typ erkannt
app1norm.xml:
```xml
  <!--       3620[ich]{ich so} <i>3620</i>] so <i>1_H.5 1_H.12 fehlt A D.1</i>  so <i>B B.a [type=2a Typ 4b]</i>-->
  <app>
    <f:replace n="3620">ich</f:replace>
    <f:ins n="3620">ich so</f:ins>
    <ref>3620</ref>
    <lem/>
    <rdg wit="1_H.5 1_H.12 A D.1">so <note><wit>1_H.5</wit> <wit>1_H.12</wit> fehlt <wit>A</wit> <wit>D.1</wit></note></rdg>
    <rdg wit="B B.a">so <note><wit>B</wit> <wit>B.a</wit> [type=2a Typ 4b]</note></rdg>
  </app>
```

> * VII: vor 2540

hier ist typ 8 in app12norm_special-cases.xml codiert

>   -- statt "vor 3187" muss es heißen "nach 3186"

dann muss das jemand dahinschreiben …

**Comment by dietmarpravida** [comment]
schon geschehen, müsste bei nächster Pushung okay sein

**Comment by gerritbruening** [comment]
vor 3187 --> nach 3186
mach ich

**Comment by gerritbruening** [comment]
Fixed by https://github.com/faustedition/faust-gen-html/commit/097d918234b52b3155d7418552575127e7b47612
