### ISSUE TITLE
IId --> IId*

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-xml#594]
This is not consistently handled in the printed volume. Also applies to the editorial introduction.

**Comment by dietmarpravida** [comment]
du meinst 10909?

**Comment by gerritbruening** [comment]
Ja

**Comment by gerritbruening** [comment]
Nach dem referencing commit bleibt noch die introduction.

**Comment by gerritbruening** [comment]
Ist alles richtig: 

https://github.com/faustedition/faust-web/blob/cb2437842120b509ba524155edd56e567a438f47/content/intro_text.html#L707

mehr gibt es nicht.
