### ISSUE TITLE
Encoding Decisions (for new TEI schema)

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-xml#595]
After preparing the first stage of the source XML transformation to current TEI (#42), there are a [number of validation errors](http://dev.digital-humanities.de/ci/view/Faust/job/faust-schema-tei-340/Validation_20Results/faust-tei.html#rng-summary) that appear to be quite systematic in the sources. For each of these, we need to decide on a policy: Should this be encoded differently? Can we convert it automatically? Or should the schema be customized to allow for this adoption? See also issue #596 for stuff that needs schema or conversion adjustments without requiring decisions first, or without being ready for decision.

* [x]  [`<hi status="name">`](http://dev.digital-humanities.de/ci/view/Faust/job/faust-schema-tei-340/Validation_20Results/faust-tei.html#d38885e59). Wiki says this is an intermediate encoding for `<name>`, so should we convert to `<name>` instead?
* [ ] invalid `<restore>`. This is mostly inside of `<subst>`. In the TEI model, `<subst>` _must_ have direct children `<add>` and `<del>`, `<restore>` as a child is not allowed.
* [x] `<gap hand='…'>`? 
* [x] `<mod type="used"/> (previously `<ge:used/>`) appears outside of zones, where it is invalid. TODO check whether this shouldn’t rather be `<modSpan>`
* [x] bare `<sic>` in diplomatic transcripts (no choice)
* [x] bare `<corr>` in diplomatic transcripts (no choice)

Apart from that, [validation results](http://dev.digital-humanities.de/ci/view/Faust/job/faust-schema-tei-340/Validation_20Results/faust-tei.html) present a number of issues which occur less than 10 times in the sources. I expect them to be encoding rather than schema issues, but it might be fruitful if you look at them.

**Comment by gerritbruening** [comment]
New encoding decisions may arise from the validation results, but we should handle these as separate issues, I think.
