### ISSUE TITLE
Check Faust I bar graphs for obvious errors

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-xml#597]
Insbesondere bei den H P... Handschriften wäre zu schauen, ob es offensichtlichen Unsinn gibt.
- [ ] z.B. ist H P1 generell falsch einsortiert, wie hier zu sehen: http://dev.faustedition.net/genesis_bargraph?rangeStart=1&rangeEnd=32
- [ ] http://dev.faustedition.net/genesis_bargraph?rangeStart=2678&rangeEnd=2804 (H.7--9 zu spät einsortiert; keine Daten?)

Wahrscheinlich wäre es aber vernünftig, hier erstmal die idnos alle sauber zu matchen, dann wird sich manches Rätsel lösen.

**Comment by dietmarpravida** [comment]
cf. #669
