### ISSUE TITLE
Lösung für Wj-Zeugnisse finden

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-xml#601]
Auf irreführende Effekte ist zu achten. Mit Hrsg zu diskutieren.

**Comment by thvitt** [comment]
Was sind Wj-Zeugnisse und worauf ist da zu achten?

**Comment by dietmarpravida** [comment]
In der Excel-Tabelle gibt es eine Spalte AJ "Zuordnung   zu „Wanderjahren“ (Trunz; aber vgl. QuZ II, S. 477f., Anm. 2)". In dieser steht bei Tagebucheinträgen, in denen Goethe vom "Hauptgeschäft" spricht, und die nach Mitte Februar 1828 datieren, ein "x". Es handelt sich um Dokumente, die bei Gräf u.a. als Faust-Dokumente gehandelt werden, die sich aber auf die „Wanderjahre“ beziehen dürften. 

Es wäre zu klären, wie diese Zeugnisse zu behandeln sind. Das einfachste wäre, sie einfach auszuschließen. Dann würden aber einige Gräf-Nummern kommentarlos entfallen, Wir könnten sie aber auch so markieren, dass sie als wahrscheinlich nicht auf Faust zu beziehende Zeugnisse kenntlich sind.

Ich sehe mir diese Einträge jetzt nochmal genauer durch.

**Comment by dietmarpravida** [comment]
Ich habe die Zeugnisse geprüft, zwei "x"-e müssten noch ergänzt werden, sonst alles okay.

[Hauptgeschäft-Zeugnisse.docx](https://github.com/faustedition/xml/files/2361285/Hauptgeschaft-Zeugnisse.docx)

**Comment by dietmarpravida** [comment]
ok, man könnte jetzt die Einträge mit x in Spalte AJ filtern

**Comment by thvitt** [comment]
[Hier](https://github.com/faustedition/faust-gen-html/commit/6b696a1f12b270f944fdcf80938aa115a0863722) nun eine Lösung, die die  entsprechenden Zeilen der Tabelle ausgraut und einen von eurem Informatiker gedichteten Hinweis auf der Detailseite einblendet. 

Weglassen geht natürlich auch. Möge die Herausgeberschaft eine Entscheidung treffen?

**Comment by dietmarpravida** [comment]
Danke! Es gibt ein Zeugnis (Gräf 1688), bei dem gar nicht klar ist, wo es zuzordnen wäre. Für die übrigen ist der Spruch okay, vielleicht aber mit etwas veränderter Reihenfoge: 

> Dieses Zeugnis ist in der älteren Forschung auf <em>Faust</em> bezogen worden; wahrscheinlich gehört es in einen anderen Zusammenhang.

**Comment by dietmarpravida** [comment]
Aus chronologischen Überrischten und dergleichen sollten die Zeugnisse jedenfalls herausgenommen werden; als Zeugnisse würde ich sie behalten wollen, schließlich gibt es in der Auseinandersetzung zwischen Trunz und Hagen noch ein oder zwei Punkte, die nie ganz ausdiskutiert worden sind.

**Comment by dietmarpravida** [comment]
erledigt?

**Comment by thvitt** [comment]
m.E. ist das mit Ausgrauen und Hinweis auf der Einzelseite implementiert. Wenn es euch und der geneigten Herausgeberschaft so passt, ist das erledigt.

**Comment by dietmarpravida** [comment]
@thvitt im Tooltip steht "Zuordnung vermutlich zu 'Wilhelm Meister Wanderjahre'", ich hätte lieber "Zeugnis gehört wahrscheinlich zu 'Wilhelm Meisters Wanderjahren'"
