### ISSUE TITLE
Compensate for loss of Hertz datings

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-xml#641]
@dietmarpravida, durch die Ignorierung der Hertz-Datierungen haben jetzt allerhand 5. Akt-Handschriften keine linksseitige Datierungsgrenze (Februar 1825 udgl.). Solche Datierungen werden aber erwartet, und man fragt, warum sie nicht erscheinen. Was machen wir: lauter `self` Datierungen desselben Inhalts anlegen?
Lese so Sachen wie
>  V H4, V H8, V H9, V H25 "stimmen in Aussehen und Schrift vollkommen überein" (faust://bibliography/hertz1932">S.256).

Ich dachte, Hertz habe keine Handschriften gesehen?

**Comment by dietmarpravida** [comment]
> lauter self Datierungen desselben Inhalts anlegen

oje, müssen wir wohl

**Comment by dietmarpravida** [comment]
Machst du eine Liste der Handschriften, für die Daten benötigt werden?

**Comment by thvitt** [comment]
ihr könnt jetzt übrigens auch in allen macrogenesetabellen sortieren (durch klicken auf den header). Leere zellen werden dabei wie sonst auch immer nach unten sortiert.

**Comment by dietmarpravida** [comment]
ich habe jetzt mal einen Haufen Datierungen eingefügt, muss aber nochmal drübersehen; @thvitt ab wann sind meine Eingaben von gerade eben sichtbar?

**Comment by thvitt** [comment]
wenn http://dev.digital-humanities.de/ci/view/Faust/job/faust-macrogen/63/ durch ist im Makrogenese-Bereich

**Comment by dietmarpravida** [comment]
danke

**Comment by gerritbruening** [comment]
Scheint durch zu sein, trotzdem https://github.com/faustedition/faust-xml/issues/663#issuecomment-427861602.

**Comment by dietmarpravida** [comment]
M.E biss auf #671 für 1.0 geklärt
