### ISSUE TITLE
mod rend="overwrite" for f:overw has whitespace issue

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-xml#648]
See https://github.com/faustedition/xml/issues/42#issuecomment-418378197.

`mod rend="overwrite"` for `f:overw` does not seem to work:
![grafik](https://user-images.githubusercontent.com/10358005/46374744-b7bd6380-c691-11e8-87f1-32cfaefaf183.png)
(2 H, p. 285)
`f:overw` is structured, `mod` is not. I see a `strip` in the table above, so is there a `strip-space` somewhere that eats those blanks?

**Comment by thvitt** [comment]
Beta: 
![selection_018](https://user-images.githubusercontent.com/1906208/46481668-2c101800-c7f4-11e8-8846-6d9056462623.png)
Ich glaub nicht dass das Rendering sich dafür interessiert ob mod oder f:overw "structured" ist oder nicht, ich hab das einfach so umgebaut dass es dasselbe macht wie vorher IIRC
d.h. kann natürlich in der nächsten konvertierugnsphase in
```xml
                <line xml:id="lab">Wollteſt <mod rend="overwrite">
                        <seg rend="under">h</seg>
                        <seg rend="over"><handShift new="#g_t"/>H</seg>
                    </mod><handShift new="#st_t"/>errliches gewinnen,</line>
```
den wsp in `<mod>` wegnehmen, aber obs davon besser wird

**Comment by gerritbruening** [comment]
> Ich glaub nicht dass das Rendering sich dafür interessiert ob mod oder f:overw "structured" ist

Doch, das denke ich schon, sonst hätte @wissenbach das `hH` rendering nicht hingekriegt, es würde überall `h H` dastehen, oder, Moritz?

**Comment by gerritbruening** [comment]
> den wsp in `<mod>` wegnehmen, aber obs davon besser wird

Wenn der Whitespace dann auch in den XML-Quellen wegfiele, fände ich das nicht gut. Zum Editieren ist die `subst`-mäßige Formatierung sehr wichtig, einfach weil innerhalb von `f:under` und `f:over` auch noch allerhand Markup steht, und wenn das alles in einer Zeile steht und bleiben muss, sieht man gar nichts mehr.
Das wäre für mich sogar ein Grund, bei `f:overw` und children zu bleiben.

**Comment by thvitt** [comment]
er scheint aber falsch zu sein, der whitespace. Du kannst es ja bei Bedarf manuell mit Whitespace innerhalb der Tags umformulieren.

Entscheidung re Whitespacewegnehmen muss heute fallen. Ich sehe im Rendering jetzt nichts, was ich da noch ändern könnte

**Comment by wissenbach** [comment]
Es wirde auch schon beim Einlesen der XML-Transkripte eine gewisse Whitespace-Behandlung vorgenommen

https://github.com/faustedition/faust-app/blob/5d9af2bf2dbe20134371dd9488cc63c0086c47c7/faust/src/main/java/de/faustedition/transcript/TranscriptTransformerConfiguration.java#L43

Ich sehe allerdings nicht, wie das beim konkreten Fall der XML-Konversion einen Unterschied machen würde. Evtl. könnte man hier testweise mal das mod-Element als <code>addWhitespaceTrimmingElement()</code> deklarieren. Nach Attribut <code>@overwrite</code> kann allerdings nicht differenziert werden.

**Comment by thvitt** [comment]
Entscheidung: `mod` enthält auch mixed content und eine Behandlung abhängig vom `rend`-Attribut geht nicht, d.h. die Änderung von `f:overw` aus https://github.com/faustedition/faust-xml/issues/42#issuecomment-418378197 wird zurückgenommen.

**Comment by thvitt** [comment]
achm ich wünste ihr würdet links in die Edition in eure Bugreports schreiben
http://dev.faustedition.net/document?sigil=2_H&page=285&view=facsimile_document#l9929
