### ISSUE TITLE
Lemma ohne A (Typ 7)

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-xml#650]
@dietmarpravida, zu Faust I gibt es zwei Einträge, wo das Lemma mit A übereinstimmt, war aber trotzde kein Zeuge angegeben ist:

https://github.com/faustedition/faust-gen-html/blob/dc9d8a43e098cc346b9999bc91f33ec584eee3a3/text/app12norm_special-cases.xml#L43

https://github.com/faustedition/faust-gen-html/commit/cbf5744a89c10e038dd4746bc5258bf4a8732def#diff-62d902c026cea28dac4c69d62caf0daaR116

Soll das so sein?
Wenn nicht, einfach sagen und mich assignen, dann ergänze ich `wit="A"` beim Lemma.

**Comment by dietmarpravida** [comment]
Bei 988 könnte man A angeben, bei 3095 sollte man eher nicht.

**Comment by gerritbruening** [comment]
Lassen wirs erstmal so.
