### ISSUE TITLE
D.1 mentioned on 2769

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-xml#652]
while it is missing here:
![grafik](https://user-images.githubusercontent.com/10358005/46469192-06bee200-c7d3-11e8-8ff6-01b34b58702f.png)

Do you want D.1 dropped online, too?

**Comment by dietmarpravida** [comment]
don't care; D2 is mentioned because D3 and D4 are, D1 is unnecessary, but can do no harm

**Comment by gerritbruening** [comment]
> Do you want D.1 dropped online, too?
