### ISSUE TITLE
2 V H.15

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/faust-xml#654]
Schreiberzuweisungen der Bibliotheksanfrage auf der Vorderseite prüfen: 

http://dev.faustedition.net/document?sigil=2_V_H.15&page=1&view=facsimile

1. Zeile: John, 2. Zeile **Schreiberhand** (recte: John?), 3. Zeile: John

**Comment by gerritbruening** [comment]
> 2. Zeile **Schreiberhand** (recte: John?)

Nur das Lateinische wird einem nicht-John zugeschrieben. Es sieht auch nicht nach ihm aus, und er wusste den Namen ja nicht. Nach Goethe siehts auch nicht aus. So lassen?

**Comment by dietmarpravida** [comment]
so lassen
