### ISSUE TITLE
change line numbers in 2 V H.12:2	

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/faust-xml#656]
`11502Vom Lager auf ihr {{Knappen}}〈: Knechte〉 Mann für Mann` **recte 11503**
`11503Laſſt glucklich ſchauen was ich kuhn erſann` **recte 11504**

**Comment by gerritbruening** [comment]
Du suchst Arbeit, will mir scheinen.
Dergleichen könnt ich dir noch mehr assignen.
