### ISSUE TITLE
rename 2 V H.37b > 2 V H.37c; 2 V H.37c > 2 V H.37b

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/faust-xml#657]
GSA 25/W 1738, bisher 2 V H.37c, neu: **2 V H.37b**
G-30.15, bisher 2 V H.37b, neu: **2 V H.37c**

ggf. ist auch die chronologische Sortierung anzupassen: neu_2 V H.37b früher als neu_2 V H.37c

**Comment by gerritbruening** [comment]
Scheint mir unproblematisch. Wenn ich was machen soll, mich re-assignen.
