### ISSUE TITLE
eliminate sigil landeck/2_V_H.h (faust/2 V H.37g)

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/faust-xml#658]
da identisch mit wa-Sigle

**Comment by gerritbruening** [comment]
Scheint es auch nur einmal zu geben:
https://faustedition.uni-wuerzburg.de/new/xml-query/?folder=macrogenesis&xpath=%2F%2F*%5B%40uri%5Bcontains%28.%2C%27landeck%2F2_V_H.h%27%29%5D%5D&mode=xml

**Comment by dietmarpravida** [comment]
in macrogenesis_v geändert;

@gerritbruening die Metadatendatei zu 391250 kann ich nicht finden, müsste auch dort zu ändern sein, da die Landeck-Sigle in archive_manuscripts angezeigt wird.

**Comment by gerritbruening** [comment]
Das ist kurios:
```xml
      <change when="2018-09-20" who="krause">idno landeck ergänzt</change>
      <change when="2018-10-08" who="bruening">Landeck idno wieder entfernt</change>
```
(`xml/document/verschiedenes/gsa_391250.xml`)
@sandrakrause, ich hoffe, ich durchkreuze da jetzt nicht etwas, was ich nicht verstanden habe?

**Comment by dietmarpravida** [comment]
äh, nein; dazu müsste ich die Datei ja gefunden haben

**Comment by sandrakrause** [comment]
Das dürfte okay sein.
Die idno wurde nur hinzugefügt, weil die Sigle in den Makrogenesedaten auftauchte und unbekannt war (um sie zu definieren).
Wenn sie da jetzt entfernt wurde, muss sie auch nicht in den Metadaten stehen.
