### ISSUE TITLE
eliminate sigil landeck/2_V_H.2

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/faust-xml#661]
identisch mit wa

**Comment by gerritbruening** [comment]
Finde `landeck_wa` in der Datei `handschriftendatierung_v.xml` nicht?

**Comment by dietmarpravida** [comment]
muss natürlich landeck/2_V_H.2 heißen

**Comment by dietmarpravida** [comment]
Die Sigle wurde von @sandrakrause erst kürzich eingefügt; ich habe sie jetzt wieder entfernt; stattdessen muss in der macrogenesis-Datei die Angabe `landeck_2 V H.2` zu `wa_2 V H.2` geändert werden.
