### ISSUE TITLE
Handle abbreviations in bibliographic entries

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-xml#664]
A:
> kann es sein, dass wir in der Bibliographie die WA gar nicht angeben? Ich finde sie nur als Kürzel, aber nicht als bibliographische Angabe?

B:
> wir weisen einzelne Bände nach, aber 
> nicht die Bedeutung der Abkürzung. Betrifft noch eine Reihe von anderen Abkürzungen.
> Wollen wir dafür den Bibliographie-Mechanismus benutzen?

C:
> der wäre da. anderes müsste erst implementiert werden. haben aber grunds. kein abk.vz.

**Comment by gerritbruening** [comment]
OK, I have made [this change in Bibliographische Verweise](https://faustedition.uni-wuerzburg.de/wiki/index.php?title=Bibliographische_Verweise&action=historysubmit&diff=50408&oldid=50407).

@thvitt, do you want me to turn all relevant entries like
```
*faust://bibliography/wa_I_1
**WA I 1
***WA, Abt. I, Bd. 1, Weimar 1887.
```
into something like
```
*faust://bibliography/wa_I_1
**WA I 1
***faust://bibliography/wa, Abt. I, Bd. 1, Weimar 1887.
```
?

**Comment by thvitt** [comment]
sollten wir mal bei einem ausprobieren, hm?

**Comment by gerritbruening** [comment]
[Gut, probiern wirs](https://faustedition.uni-wuerzburg.de/wiki/index.php?title=Bibliographische_Verweise&action=historysubmit&diff=50412&oldid=50411)

**Comment by thvitt** [comment]
Das wird jetzt so aussehen:

![screenshot_140](https://user-images.githubusercontent.com/1906208/46636674-42ea9d80-cb59-11e8-9f20-7acecd771ef2.png)

und weiter unten:

![screenshot_141](https://user-images.githubusercontent.com/1906208/46636679-4716bb00-cb59-11e8-8fb6-f6024df74d50.png)

**Comment by gerritbruening** [comment]
Schick!
Soll ich ein großes Suchen und Ersetzen über die Wiki-Seite machen?

**Comment by thvitt** [comment]
ja mach. `*** WA,` sollte’s ja tun

**Comment by gerritbruening** [comment]
[Ist gemacht](https://faustedition.uni-wuerzburg.de/wiki/index.php?title=Bibliographische_Verweise&action=historysubmit&diff=50413&oldid=50412).
