### ISSUE TITLE
Line numbering of P97ff.

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-xml#666]
To enable for https://github.com/faustedition/faust-web/issues/135.

**Comment by gerritbruening** [comment]
H P97, H P98 und V H.2 habe ich jetzt so bearbeitet, dass die Zeilensynopse für die beiden Paralipomena funktionieren sollte.

**Comment by gerritbruening** [comment]
Ich habe in H P97
`<l f:nx="p97_1">Den beſten Köpfen ſey das Stück empfohlen</l>`
und in V H.2
`<l f:nx="p97_1">Den beſten Köpfen ſey das Stück empfohlen</l>`
usw.
Vorher stand `@n` da.
Trotzdem wird erscheint noch keine Synopse. Kann es sein, dass Zahl-Unterstrich-Zahl ein Problem ist, @thvitt?

**Comment by thvitt** [comment]
ich glaube, es liegt eher daran, dass n-Attribute mit einem `p` drin explizit ausgeschlossen wurden (genauso wie solche mit einem `todo`).

**Comment by gerritbruening** [comment]
Ach Mist, das hatte ich nicht begriffen.
`p` entfernen?

**Comment by thvitt** [comment]
warum war denn das p verboten? ich kann es auch einfach erlauben.

**Comment by gerritbruening** [comment]
Dann sieht die Welt schon wieder besser aus!
