### ISSUE TITLE
Obertitel von WA in die Bibliographie

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/faust-xml#667]
https://github.com/faustedition/faust-xml/issues/622#issuecomment-427921195

**Comment by dietmarpravida** [comment]
WA 
Goethes Werke. Herausgegeben im Auftrage der Großherzogin Sophie von Sachsen, IV Abteilungen, 133 Bde., Weimar 1877–1919.

**Comment by thvitt** [comment]
da hat doch @gerritbruening irgendwas parallel gemacht? Er hat einen Eintrag im Wiki angelegt und wollte die einzelnen Bände drauf referenzieren lassen IIRC

**Comment by gerritbruening** [comment]
> da hat doch @gerritbruening irgendwas parallel gemacht?

https://github.com/faustedition/faust-xml/issues/664
Siehe auch https://github.com/faustedition/faust-gen-html/issues/602#issuecomment-425088123.

**Comment by dietmarpravida** [comment]
@gerritbruening Wie soll das im Wiki aussehen?

**Comment by gerritbruening** [comment]
[So](https://faustedition.uni-wuerzburg.de/wiki/index.php?title=Bibliographische_Verweise&action=historysubmit&diff=50413&oldid=50412)
