### ISSUE TITLE
missing bibliography entries from macrogenesis

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-xml#672]
there are a few unresolved bibliography links left, [see the sources page](http://dev.faustedition.net/macrogenesis/sources)

- [x] * Jensen1968
- [x] * wa_i_15_2 
- [x] * bohnenkamp
- [x] * document-scheibe1974
- [x] * bibliography-wa_I_15_2

**Comment by thvitt** [comment]
wird auf zuruf durch mich aus dem wiki gezogen, so wie die entstehungszeugnistabelle

http://dev.faustedition.net/macrogenesis/sources sagt es gibt 54 aussagen mit bohnenkamp und 566 mit bohnenkamp1994, ich würd sagen letzteres gewinnt, ersteres bitte ersetzen

**Comment by dietmarpravida** [comment]
> bitte ersetzen

@gerritbruening

**Comment by gerritbruening** [comment]
@dietmarpravida, hier liegt das Zeug:
https://github.com/faustedition/faust-xml/tree/master/xml/macrogenesis

**Comment by dietmarpravida** [comment]
@gerritbruening wa_i_15_2 in den wa/15_2/...-Dateien machst bitte du

**Comment by dietmarpravida** [comment]
@thvitt kannst du bitte die Liste aktualisieren?

**Comment by gerritbruening** [comment]
> @gerritbruening `wa_i_15_2`  in den `wa/15_2/...`-Dateien machst bitte du

Das hat @thvitt schon im Rahmen von https://github.com/faustedition/faust-macrogen/issues/16 behandelt.
Gibt es sonst noch was zu tun, @dietmarpravida?

**Comment by thvitt** [comment]
das letzte (aktuelle) Bibliographieupdate vom Wiki war https://github.com/faustedition/faust-gen-html/commit/c1307a9

**Comment by dietmarpravida** [comment]
scheint nicht mehr aktuell, oder? schließen?
