### ISSUE TITLE
macrogen schema reference still points to Wuerzburg

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-xml#676]
It says `https://faustedition.uni-wuerzburg.de/xml/schema/macrogenesis.xsd`

**Comment by thvitt** [comment]
where should it point? rawgithub? faustedition.net/schema?

**Comment by thvitt** [comment]
no, this issue is about the macrogenesis files, and they shouldn’t validate against faust-tei.rng

**Comment by gerritbruening** [comment]
Sorry, confused this with https://github.com/faustedition/faust-schema/issues/9.

**Comment by thvitt** [comment]
There’s `macrogenesis.rnc` beside the sources now
