### ISSUE TITLE
Fehlerhafte Verlinkung bei Entstehungszeugnissen mit ID "lfd-nr-xy"

### ISSUE THREAD

**Issue by sandrakrause** [faustedition/faust-xml#697]
Mir ist aufgefallen, dass einige Entstehungszeugnisse ohne eindeutige ID (also die, die wir als lfd-nr betitelt haben), keine richtigte Verlinkung haben, wenn man auf den Auszug klickt.
Sie verweisen auf den testimony-Index http://faustedition.net/testimony/
(z.B. 09.1774 | Brief von Johann Kaspar Lavater an Johann Wolfgang Goethe | … Faust – ein par Stellen draus …)

Außerdem ist mir noch folgendes aufgefallen:
Bisher haben wir die ID ja mit lfd-nr-neuneu_x angegeben.
Offenbar existieren nebenher aber auch IDs mit lfd-nr-neu_2_x.
(z.B. verlinkt 01.1775 | Gesprächsbericht von Karl Ludwig von Knebel auf http://faustedition.net/testimony/lfd-nr-neu-2_15 statt auf neuneu_15, wie es im xml vergeben wurde.)
Soll lfd-nr-neu_2 der neue Standard werden? Müssen die IDs im xml dann geändert werden?
Sonst scheint die Anzeige nicht zu funktionieren, wenn man sich zum Vergleich
http://faustedition.net/testimony/lfd-nr-neu-2_9.html
und
http://faustedition.net/testimony/lfd-nr-neuneu_9.html
anschaut.

Vielleicht wird da auch gerade was dran gebastelt, dann will ich natürlich nichts gesagt haben.

**Comment by thvitt** [comment]
* https://github.com/faustedition/faust-gen-html/commit/d25966d487d99704bca1cbda601169dcddabd91b sollte die Links nach testimony/ lösen
* Das Knebelproblem entsteht, weil kein Testimony-div gefunden wurde in dem TEI → @sandrakrause, `<div>` um den relevanten Entstehungszeugnisbereich ergänzen 

Diese ganze lfd-nr-*-Geschichte ist eine ziemlich schlechte ID – aber es müsste eigentlich funktionieren. D.h. wenn um den Knebel ein div wäre, würde die tatsächlich verwendete ID als solche erkannt & auch der link sollte dann korrekt funktionieren.
