### ISSUE TITLE
contradicting faust://self assertions on H P98

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-xml#698]
Die Aussagen [H P98 _nicht vor_ 1800-04-13](http://dev.faustedition.net/macrogenesis/1800-04-12--H_P98) widersprechen den Aussagen [H P98](http://dev.faustedition.net/macrogenesis/H_P98) _nicht nach_ 1798-05-05 (Bohnenkamp 1994 S.213 | Papier und Duktus. . . / 1797/1798 | handschriftendatierung_pre1800.xml: 580). Beide Aussagen sind mit `faust://self` markiert.

**Comment by dietmarpravida** [comment]
Die Zeile 607 scheint ein Irrläufer, denn wir vertreten diese Datierung Graefs (und Pniowers) eigentlich nicht
