### ISSUE TITLE
Relation type missing for some Fischer-Lamberg relations

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-xml#699]
Is this `kind="temp-pre"`?

https://github.com/faustedition/faust-xml/blob/98fabe3b7021a06811f3da0cc88f29d9473c2631/xml/macrogenesis/fischer-lamberg/III.xml#L211-L228

(Cf. https://github.com/faustedition/faust-macrogen/issues/11)

**Comment by dietmarpravida** [comment]
i think so, anteriority in linear order is to be read as genetic precedence
