### ISSUE TITLE
<note> tag abuse? (Dok. Transkript 2 II H.13 S. 2)

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-xml#707]
`<note>` außerhalb `<line>` [wird zwar nicht angezeigt](http://faustedition.net/document?sigil=2_II_H.13&page=2&view=document), aber sonstige notes in den dok. Transcripten sind tatsächlich auf dem Blatt zu finden und von einer hand. 

https://github.com/faustedition/faust-xml/blob/e90004367ac2a046e30e87af5467c240d5471643/xml/transcript/gsa/390208/0004.xml#L337

Vielleicht einfach ein Kommentar oder ein `<rdg>` oder so?

**Comment by gerritbruening** [comment]
Hintergrund ist folgende Festlegung: https://faustedition.uni-wuerzburg.de/wiki/index.php/Kodierungsregeln#Kommentierung_erl.C3.A4uterungsbed.C3.BCrftiger_Stellen

`rdg` trifft es nicht ganz, denke ich. Ob der von dir entdeckte Usus ganz ideal ist, müsste man mit Blick auf kommende Projekte überlegen. Grundätzlich habe ich aber den Eindruck, das `note` laut TEI sowohl für vorgefindene Anmerkungen als auch für Äußerungen der Kodierenden anwendbar ist.

**Comment by thvitt** [comment]
Das im Wiki geforderte `type="editorial"` fehlt aber auch an der Stelle. Weiß nicht mehr, in welchem Kontext ich darauf gestoßen bin, aber ich finde, dass man irgendwie explizit machen sollte, dass diese Note _nicht_ auf dem Blatt steht.

**Comment by gerritbruening** [comment]
Ja, jede `note` für die gilt:
- `ancestor` ist `sourceDoc` und
- `ancestor` ist nicht `line`,

sollte `type="editorial"` erhalten.

**Comment by gerritbruening** [comment]
I am searching for `//note[ancestor::sourceDoc and not(ancestor::line) and not(@type='editorial')]` on my working set `faust-xml`. Seems to take quite a while.
