### ISSUE TITLE
broken facsimile links

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-xml#710]
During https://github.com/faustedition/faust-web/issues/285 it occurred the following pages contain invalid facsimile links. To fix, click the link to the _broken\_img_ column, remove the part after the last `/` and look for the correct file. Then click the link in the `sigil` column  and use _Download -> Dokumentarisches Transkript_ in the edition to find the TEI file to edit.

| sigil                                                                                     | page | broken\_img                                                                                                                  |
|-------------------------------------------------------------------------------------------|-----:|------------------------------------------------------------------------------------------------------------------------------|
| [2 III H.79](http://dev.faustedition.net/document?sigil=2_III_H.79&page=1&view=facsimile) |    1 | [gsa/390567/25_W 1665_BL1v](http://dev.faustedition.net/transcript/facsimile/jpg/gsa/390567/25_W%201665_BL1v_0.jpg)           |
| [2 V H.2](http://dev.faustedition.net/document?sigil=2_V_H.2&page=18&view=facsimile)      |   18 | [gsa/390883/GSA-W-1618-a](http://dev.faustedition.net/transcript/facsimile/jpg/gsa/390883/GSA-W-1618-a_0.jpg)                |
| [2 V H.2](http://dev.faustedition.net/document?sigil=2_V_H.2&page=18&view=facsimile)      |   18 | [gsa/390883/GSA-W-1618-b](http://dev.faustedition.net/transcript/facsimile/jpg/gsa/390883/GSA-W-1618-b_0.jpg)                |
| [2 V H.2](http://dev.faustedition.net/document?sigil=2_V_H.2&page=18&view=facsimile)      |   18 | [gsa/390883/GSA-W-1618-c](http://dev.faustedition.net/transcript/facsimile/jpg/gsa/390883/GSA-W-1618-c_0.jpg)                |
| [D.1](http://dev.faustedition.net/document?sigil=D.1&page=109&view=facsimile)             |  109 | [print/D(1)_IV3-1/1)_IV3-1_105](http://dev.faustedition.net/transcript/facsimile/jpg/print/D\(1\)_IV3-1/1\)_IV3-1_105_0.jpg) |
| [D.1](http://dev.faustedition.net/document?sigil=D.1&page=109&view=facsimile)             |  109 | [print/D(1)_IV3-1/D(](http://dev.faustedition.net/transcript/facsimile/jpg/print/D\(1\)_IV3-1/D\(_0.jpg)                     |

**Comment by thvitt** [comment]
kann ich dir das geben zur Identifikation der korrekten Digitalisate, bin be bedarf gern behilflich. Die Dateien auf `_0.jpg` sind die höchste Auflösung, das dann natürlich weglassen im TEI …

**Comment by gerritbruening** [comment]
https://github.com/faustedition/faust-xml/commit/f202a7dcbd0e7d2ab7ad1a86bd8547b34c75e030#diff-1ad81e01c7b3e752c962c4e2ce6413152baa34cc9f256ba19bd8f156ffec3bc9R318

has still whitespace within `@url`. Isn't this illegal?
