### ISSUE TITLE
Transform `f:proposedBy` etc. into canonical TEI?

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-xml#717]
We still have `f` namespace attributes in the encoding. Ideally we would get rid of these. We could claim that our text data is completely canonic with the new release.
I think that `mod`s pointing to the respective `subst` and the like would be most appropriate. `@target` on `mod` is not allowed yet. `@corresp` is allowed, but it may be slightly abusive to use it, at least the meaning would be less clear. Do you think that `mod` + `@type` + `@target` would be feasible and apt? If so, I would ask TEIC wether `@target` may be allowed on `mod`.

**Comment by thvitt** [comment]
No.

As far as I understand [from the guidelines](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/PH.html#PH-mod), `<mod>` is intended to encode _less_ semantics, i.e. a modification without interpreting that it is an addition etc. That’s why it is in the primary sources section, isn't it? Additionally, it would make encoding more indirect and complex.

**Comment by gerritbruening** [comment]
I agree that the Guideline's prose is quite restrictive, while the pure [definition](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-mod.html) is not. 

> That’s why it is in the primary sources section, isn't it? 

Not quite, the chapter has many interpretive stuff, not just purely documentary. 

> Additionally, it would make encoding more indirect and complex.

That's true, and I would like to avoid this, too. The current attributes on the respective revision elements are more direct and more elegant. It's only my interest in  canonical solutions that made me think about changing this. Do you imply it's best to keep data as it is?

**Comment by thvitt** [comment]
I do not think it is a goal to get rid of all project specific encoding; if there is no obvious, explicit and standardized way to encode this information in TEI, then a project specific customization in a separate namespace seems to be the way to go.

**Comment by gerritbruening** [comment]
OK, thanks for these comments which I find pretty convincing. It would mean that we would re-use some `f` namespace attributes in the next project.
