### ISSUE TITLE
Missing XML in GSA 391098

### ISSUE THREAD

**Issue by th-schmidt** [faustedition/faust-xml#722]
If I am not mistaken, there is one XML missing in `faust-xml` > `xml` > `gsa` > `391098`. I am looking for the transcript of scan `391098_0177c_0.jpg` which should be named `0177c.xml`, but there is none such file.

Any help would be appreciated!

**Comment by gerritbruening** [comment]
The transcript for `0177c_0.jpg` is included in `0177a.xml`, see

https://github.com/faustedition/faust-xml/blob/a667983f33b96c14826d5aa92164645e70454ff1/xml/transcript/gsa/391098/0177a.xml#L316

The transcript of this image (i.e. of the back of the patch) is here:

https://github.com/faustedition/faust-xml/blob/a667983f33b96c14826d5aa92164645e70454ff1/xml/transcript/gsa/391098/0177a.xml#L422-L454
