### ISSUE TITLE
encoding error in 2 III H.64e

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-xml#729]
doctranscript translation issues this warning:

```
#18 135.9 WARNING: Conversion to SVG for 2 III H.64e issued messages:
#18 135.9 Error: Evaluation failed: ENCODING ERROR: Reference to #li cannot be resolved!
```

https://github.com/faustedition/faust-xml/tree/1.3-RC/xml/transcript/gm_duesseldorf/KK123_20

**Comment by gerritbruening** [comment]
Isn't this fixed in https://github.com/faustedition/faust-xml/commit/7cbf7a3017b59b6e84038529a13a3604a84b2c82?

**Comment by thvitt** [comment]
sorry, appearently it is and I just had an old version of the XML files.
